# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DY_E_cVY7Mg2USbSl8j0QOZ-agm0dNwG
"""

metodos_pagamento = [
    [1, "Cartão de Crédito", True],
    [2, "Boleto Bancário", True],
    [3, "PIX", True],
    [4, "Dinheiro", False],
    [5, "Paypal", True]
]

def listar_metodos_ativos(metodos):
    print("Métodos de pagamento ativos:")
    for metodo in metodos:
        codigo, nome, ativo = metodo
        if ativo:
            print(f"{codigo} - {nome}")

def buscar_metodo_por_codigo(metodos, codigo_busca):
    for metodo in metodos:
        codigo, nome, ativo = metodo
        if codigo == codigo_busca:
            return metodo
    return None

listar_metodos_ativos(metodos_pagamento)

codigo = int(input("Digite o código do método de pagamento desejado: "))
metodo_selecionado = buscar_metodo_por_codigo(metodos_pagamento, codigo)

if metodo_selecionado:
    codigo, nome, ativo = metodo_selecionado
    status = "ativo" if ativo else "inativo"
    print(f"Método selecionado: {nome} (Status: {status})")
else:
    print("Método de pagamento não encontrado.")