# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DY_E_cVY7Mg2USbSl8j0QOZ-agm0dNwG
"""

usuarios_logados = []

def logar_usuario(nome, email):
  usuario = {
      "nome": nome,
      "email": email
  }
  usuarios_logados.append(usuario)
  print(f"Usuário {nome} logado com sucesso!")

logar_usuario("João", "joao@email.com")
logar_usuario("Maria", "maria@email.com")

print("Usuários logados:")
for usuario in usuarios_logados:
  print(f"- {usuario['nome']} ({usuario['email']})")